print('====== DESAFIO 06 ======')
valor = int(input('Digite um número: '))
print('O dobro de ',valor,' é: ',valor+valor)
print('O triplo de ',valor,' é: ',3*valor)
print('A raiz quadrada de ',valor,' é: ',valor**1/3)
